"""Visual identity: palette, global CSS, Plotly template and small HTML builders."""

from __future__ import annotations

from html import escape
from urllib.parse import quote
from typing import Iterable, Sequence

import plotly.graph_objects as go
import plotly.io as pio
import streamlit as st

PAPER = "#F2EDE3"
PAPER_2 = "#E8E0CF"
RULE = "#D3C8B2"
INK = "#16232A"
INK_SOFT = "#4E5D63"
SUN = "#E59A2B"
SUN_DEEP = "#C9731B"
SEA = "#2D6A8A"
SEA_LIGHT = "#8CB8C9"
LEAF = "#1F5E57"
EMBER = "#C4513A"
VIOLET = "#6C5BA7"
STONE = "#A79F90"

MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

SOURCE_COLOR = {"solar": SUN, "wind": SEA, "combined": LEAF}
SITE_COLOR = {
    "Laoag, Ilocos Norte": SEA,
    "Mactan, Cebu": SUN_DEEP,
    "General Santos City": LEAF,
}
MODEL_COLOR = {"xgboost": LEAF, "previous_day": VIOLET, "training_climatology": STONE}

FONT_BODY = "Instrument Sans, sans-serif"
FONT_MONO = "JetBrains Mono, monospace"
FONT_HEAD = "Fraunces, serif"

# Fine paper grain, generated by an SVG turbulence filter.
_GRAIN_SVG = (
    "<svg xmlns='http://www.w3.org/2000/svg' width='220' height='220'>"
    "<filter id='n'><feTurbulence type='fractalNoise' baseFrequency='.9' numOctaves='2' stitchTiles='stitch'/>"
    "<feColorMatrix values='0 0 0 0 .09  0 0 0 0 .13  0 0 0 0 .16  0 0 0 .06 0'/></filter>"
    "<rect width='100%' height='100%' filter='url(#n)'/></svg>"
)
# Percent-encoded: Streamlit's sanitizer drops any <style> whose text contains markup.
_GRAIN = f'url("data:image/svg+xml,{quote(_GRAIN_SVG)}")'

CSS = f"""
<style>
:root {{
  --paper:{PAPER}; --paper2:{PAPER_2}; --rule:{RULE}; --ink:{INK}; --ink-soft:{INK_SOFT};
  --sun:{SUN}; --sun-deep:{SUN_DEEP}; --sea:{SEA}; --sea-light:{SEA_LIGHT}; --leaf:{LEAF};
  --ember:{EMBER}; --violet:{VIOLET}; --stone:{STONE};
  --mono:'JetBrains Mono', ui-monospace, monospace; --serif:'Fraunces', Georgia, serif;
}}
.stApp {{ background-color:var(--paper); background-image:{_GRAIN}; }}
[data-testid="stMainBlockContainer"] {{ max-width:1240px; padding-top:4.6rem; padding-bottom:5rem; }}
[data-testid="stHeader"] {{ background:rgba(242,237,227,.88); backdrop-filter:blur(10px);
  border-bottom:1px solid var(--rule); }}
[data-testid="stDecoration"] {{ display:none; }}
h1, h2, h3 {{ letter-spacing:-.02em; }}


/* top navigation */
[data-testid="stHeader"] a[href] {{ font-weight:600; letter-spacing:.01em; }}

/* metric tiles: ruled, almanac style */
[data-testid="stMetric"] {{ background:rgba(255,253,248,.62); border:1px solid var(--rule);
  border-top:3px solid var(--ink); border-radius:2px 2px 10px 10px; padding:.8rem 1rem .7rem; }}
[data-testid="stMetricLabel"] p {{ font-family:var(--mono); font-size:.72rem !important; text-transform:uppercase;
  letter-spacing:.08em; color:var(--ink-soft); }}
[data-testid="stMetricValue"], [data-testid="stMetricValue"] * {{ font-family:var(--serif) !important; font-weight:600; font-size:1.9rem; }}
[data-testid="stMetricDelta"] {{ font-family:var(--mono); font-size:.75rem; }}

/* bordered containers become instrument panels */
[data-testid="stVerticalBlockBorderWrapper"]:has(> div > [data-testid="stVerticalBlock"]) {{
  background:rgba(255,253,248,.5); }}
.stTabs [data-baseweb="tab-list"] {{ gap:.25rem; border-bottom:1px solid var(--rule); }}
.stTabs [data-baseweb="tab"] {{ font-family:var(--mono); font-size:.8rem; text-transform:uppercase; letter-spacing:.06em; }}
[data-testid="stCaptionContainer"] {{ color:var(--ink-soft); }}
[data-testid="stPageLink"] a {{ border:1px solid var(--ink); border-radius:999px; padding:.35rem 1rem;
  background:var(--paper); transition:transform .2s, background .2s; }}
[data-testid="stPageLink"] a:hover {{ background:var(--ink); transform:translateY(-2px); }}
[data-testid="stPageLink"] a:hover p, [data-testid="stPageLink"] a:hover span {{ color:var(--paper) !important; }}
[data-testid="stExpander"] details {{ border-radius:10px; background:rgba(255,253,248,.45); }}
[data-testid="stPlotlyChart"] {{ border-top:1px solid var(--rule); padding-top:.3rem; }}

/* section headers */
.hb-kicker {{ font-family:var(--mono); font-size:.74rem; letter-spacing:.14em; text-transform:uppercase;
  color:var(--sun-deep); display:flex; align-items:center; gap:.6rem; margin:0 0 .35rem; }}
.hb-kicker:before {{ content:""; width:28px; height:1px; background:currentColor; }}
.hb-title {{ font-family:var(--serif); font-size:clamp(1.9rem,3.6vw,2.8rem); line-height:1.05; color:var(--ink);
  margin:0 0 .6rem; font-weight:600; letter-spacing:-.025em; }}
.hb-title em {{ font-style:italic; color:var(--sea); font-weight:500; }}
.hb-lede {{ color:var(--ink-soft); font-size:1.06rem; max-width:760px; line-height:1.55; margin:0 0 1.2rem; }}
.hb-note {{ border-left:3px solid var(--sun); background:rgba(229,154,43,.08); padding:.75rem 1rem;
  border-radius:0 8px 8px 0; color:var(--ink-soft); font-size:.93rem; line-height:1.5; }}
.hb-note b {{ color:var(--ink); }}

/* count-up figures (pure CSS, no JS) */
@property --hb-n {{ syntax:'<integer>'; initial-value:0; inherits:false; }}
.hb-stats {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); border-top:1px solid var(--ink);
  border-bottom:1px solid var(--ink); margin:1.4rem 0 2.2rem; }}
.hb-stat {{ padding:1.1rem 1.2rem 1rem; border-right:1px solid var(--rule); }}
.hb-stat:last-child {{ border-right:0; }}
.hb-stat .num {{ font-family:var(--serif); font-size:clamp(2rem,4vw,3.1rem); font-weight:600; line-height:1; color:var(--ink);
  letter-spacing:-.03em; }}
.hb-stat .num i {{ font-style:normal; counter-reset:hb var(--hb-n); animation:hb-count 2.4s cubic-bezier(.16,.84,.24,1) forwards; }}
.hb-stat .num i::after {{ content:counter(hb); }}
.hb-stat .num small {{ font-size:.5em; color:var(--sun-deep); margin-left:.1em; }}
.hb-stat p {{ margin:.55rem 0 0; color:var(--ink-soft); font-size:.88rem; line-height:1.4; }}
@keyframes hb-count {{ from {{ --hb-n:0; }} to {{ --hb-n:var(--to); }} }}
/* thousands separator: animate thousands and a zero-padded remainder separately */
@property --hb-k {{ syntax:'<integer>'; initial-value:0; inherits:false; }}
@counter-style hb-pad3 {{ system:extends decimal; pad:3 "0"; }}
.hb-stat .num i.k {{ counter-reset:hbk var(--hb-k) hb var(--hb-n); animation-name:hb-count-k; }}
.hb-stat .num i.k::after {{ content:counter(hbk) "," counter(hb, hb-pad3); }}
@keyframes hb-count-k {{ from {{ --hb-k:0; --hb-n:0; }} to {{ --hb-k:var(--tk); --hb-n:var(--to); }} }}

/* site cards */
.hb-sites {{ display:grid; grid-template-columns:repeat(3,minmax(0,1fr)); gap:1rem; margin:.4rem 0 1.6rem; }}
.hb-site {{ position:relative; border:1px solid var(--rule); border-radius:14px; padding:1.1rem 1.15rem 1rem;
  background:rgba(255,253,248,.6); overflow:hidden; transition:transform .3s, box-shadow .3s; }}
.hb-site:hover {{ transform:translateY(-4px); box-shadow:0 18px 40px -22px rgba(22,35,42,.45); }}
.hb-site .tag {{ font-family:var(--mono); font-size:.7rem; letter-spacing:.1em; text-transform:uppercase; color:var(--ink-soft); }}
.hb-site h4 {{ font-family:var(--serif); font-size:1.45rem; margin:.15rem 0 .25rem; padding:0; color:var(--ink); }}
.hb-site p {{ font-size:.86rem; color:var(--ink-soft); margin:0 0 .7rem; min-height:2.5em; }}
.hb-site .row {{ display:flex; gap:1.2rem; font-family:var(--mono); font-size:.78rem; color:var(--ink); }}
.hb-site .row b {{ display:block; font-family:var(--serif); font-size:1.35rem; font-weight:600; }}
.hb-site svg {{ display:block; width:100%; height:64px; margin-top:.6rem; }}
.hb-site svg .line {{ stroke-dasharray:600; stroke-dashoffset:600; animation:hb-draw 2.2s .3s ease forwards; }}
@keyframes hb-draw {{ to {{ stroke-dashoffset:0; }} }}

/* pipeline steps */
.hb-steps {{ display:grid; grid-template-columns:repeat(4,minmax(0,1fr)); gap:0; margin:.6rem 0 2rem; position:relative; }}
.hb-step {{ padding:1rem 1.1rem 0 0; position:relative; }}
.hb-step .n {{ font-family:var(--mono); font-size:.72rem; color:var(--paper); background:var(--ink); border-radius:999px;
  width:1.7rem; height:1.7rem; display:grid; place-items:center; position:relative; z-index:1; }}
.hb-step:not(:last-child):after {{ content:""; position:absolute; top:1.85rem; left:1.8rem; right:.4rem; height:1px;
  background:repeating-linear-gradient(90deg,var(--ink) 0 6px,transparent 6px 12px); background-size:24px 1px;
  animation:hb-march 1.2s linear infinite; }}
.hb-step h5 {{ font-family:var(--serif); font-size:1.12rem; margin:.7rem 0 .25rem; padding:0; color:var(--ink); }}
.hb-step p {{ font-size:.86rem; color:var(--ink-soft); margin:0; line-height:1.45; }}
@keyframes hb-march {{ to {{ background-position:24px 0; }} }}

.hb-two {{ display:grid; grid-template-columns:1fr 1fr; gap:1rem; }}
.hb-card {{ border:1px solid var(--rule); border-radius:12px; padding:1rem 1.1rem; background:rgba(255,253,248,.55); }}
.hb-card h5 {{ font-family:var(--mono); font-size:.74rem; letter-spacing:.1em; text-transform:uppercase; margin:0 0 .5rem; }}
.hb-card ul {{ margin:0; padding-left:1.1rem; color:var(--ink-soft); font-size:.92rem; line-height:1.55; }}
.hb-foot {{ margin-top:3rem; padding-top:1rem; border-top:1px solid var(--ink); display:flex; justify-content:space-between;
  gap:1rem; flex-wrap:wrap; font-family:var(--mono); font-size:.72rem; color:var(--ink-soft); letter-spacing:.04em; }}

@media (max-width: 860px) {{
  .hb-stats {{ grid-template-columns:repeat(2,minmax(0,1fr)); }}
  .hb-stat:nth-child(2) {{ border-right:0; }}
  .hb-stat:nth-child(-n+2) {{ border-bottom:1px solid var(--rule); }}
  .hb-sites, .hb-steps, .hb-two {{ grid-template-columns:1fr; }}
  .hb-step:after {{ display:none; }}
}}
@media (prefers-reduced-motion: reduce) {{
  *, *:before, *:after {{ animation-duration:.01ms !important; animation-iteration-count:1 !important; }}
}}
</style>
"""


def html(markup: str) -> None:
    """Render trusted inline HTML/SVG. st.html strips SVG, so use markdown with
    whitespace collapsed (indented lines would otherwise become code blocks)."""
    st.markdown(" ".join(line.strip() for line in markup.splitlines()), unsafe_allow_html=True)


def inject() -> None:
    html(CSS)


def _template() -> go.layout.Template:
    axis = dict(
        gridcolor="rgba(22,35,42,.08)",
        linecolor=INK,
        tickcolor=INK,
        ticks="outside",
        ticklen=4,
        zeroline=False,
        title=dict(font=dict(family=FONT_MONO, size=11, color=INK_SOFT)),
        tickfont=dict(family=FONT_MONO, size=11, color=INK_SOFT),
    )
    return go.layout.Template(
        layout=dict(
            font=dict(family=FONT_BODY, color=INK, size=13),
            title=dict(font=dict(family=FONT_HEAD, size=19, color=INK), x=0, xanchor="left", y=.97),
            paper_bgcolor="rgba(0,0,0,0)",
            plot_bgcolor="rgba(0,0,0,0)",
            colorway=[SUN, SEA, LEAF, EMBER, VIOLET, STONE],
            xaxis=axis,
            yaxis=axis,
            legend=dict(
                orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1,
                font=dict(family=FONT_MONO, size=11), bgcolor="rgba(0,0,0,0)",
            ),
            hoverlabel=dict(bgcolor=INK, font=dict(family=FONT_MONO, color=PAPER, size=12), bordercolor=INK),
            margin=dict(l=10, r=10, t=60, b=10),
            hovermode="x unified",
        )
    )


pio.templates["habagat"] = _template()
pio.templates.default = "habagat"


def style(fig: go.Figure, title: str = "", y: str = "", height: int = 400) -> go.Figure:
    fig.update_layout(title=title, height=height)
    if y:
        fig.update_layout(yaxis_title=y)
    return fig


def chart(fig: go.Figure, key: str | None = None) -> None:
    st.plotly_chart(fig, key=key, config={"displayModeBar": False})


def header(kicker: str, title: str, lede: str = "") -> None:
    lede_html = f'<p class="hb-lede">{lede}</p>' if lede else ""
    html(f'<div class="hb-kicker">{escape(kicker)}</div><h2 class="hb-title">{title}</h2>{lede_html}')


def note(text: str) -> None:
    html(f'<div class="hb-note">{text}</div>')


def stats(items: Iterable[tuple[int, str, str]]) -> None:
    """Animated count-up strip: (integer value, unit suffix, caption)."""
    def figure(value: int) -> str:
        if value >= 1000:
            return f'<i class="k" style="--tk:{value // 1000};--to:{value % 1000}"></i>'
        return f'<i style="--to:{value}"></i>'

    cells = "".join(
        f'<div class="hb-stat"><div class="num">{figure(int(value))}'
        f'<small>{escape(unit)}</small></div><p>{caption}</p></div>'
        for value, unit, caption in items
    )
    html(f'<div class="hb-stats">{cells}</div>')


def sparkline(values: Sequence[float], color: str, width: int = 300, height: int = 64) -> str:
    lo, hi = min(values), max(values)
    span = (hi - lo) or 1.0
    step = width / (len(values) - 1)
    points = [(i * step, height - 6 - (v - lo) / span * (height - 14)) for i, v in enumerate(values)]
    line = " ".join(f"{x:.1f},{y:.1f}" for x, y in points)
    area = f"M0,{height} L" + " L".join(f"{x:.1f},{y:.1f}" for x, y in points) + f" L{width},{height} Z"
    months = "".join(
        f'<text x="{i * step:.1f}" y="{height - 1}" font-size="8" fill="{INK_SOFT}" '
        f'font-family="JetBrains Mono" text-anchor="{"start" if i == 0 else "end" if i == 11 else "middle"}">{m}</text>'
        for i, m in enumerate("JFMAMJJASOND")
    )
    return (
        f'<svg viewBox="0 0 {width} {height}" preserveAspectRatio="none">'
        f'<path d="{area}" fill="{color}" opacity=".13"/>'
        f'<polyline class="line" points="{line}" fill="none" stroke="{color}" stroke-width="2" '
        f'vector-effect="non-scaling-stroke"/>{months}</svg>'
    )


def footer() -> None:
    html(
        '<div class="hb-foot"><span>HABAGAT · CSS142 RESEARCH PROTOTYPE</span>'
        "<span>Weather: NASA POWER · Turbine: EWT DW61 (NLR curve) · Reference modeled output, not metered plant data</span></div>"
    )
